name: Holidaysofme
favicon: null
layout_spectrum: 0.24165955069474876
typography_spectrum: 0.9969550704117864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.30260696774348617
  lightness: 0.6338028323370963
  saturation: 0.31191914970986545
  rhythmicContrast: 0.6150848856195807
purpose: []
